stages:
    data_injection:
        cmd: python src\CNNClassifier\pipeline\stage_01_data_ingestion.py
        deps:
            - src\CNNClassifier\pipeline\stage_01_data_ingestion.py
            - config\config.yaml
        outs:
            - artifacts\data_injection\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone

    prepare_base_model:
        cmd: python src\CNNClassifier\pipeline\stage_02_prepare_base_model.py
        deps:
            - src\CNNClassifier\pipeline\stage_02_prepare_base_model.py
            - config\config.yaml
        params:
            - IMAGE_SIZE
            - CLASSES
            - EPOCHS
            - BATCH_SIZE
            - LEARNING_RATE
        outs:
            - artifacts\prepare_base_model\base_model.h5
    
    training:
        cmd: python src\CNNClassifier\pipeline\stage_03_model_training.py
        deps:
            - src\CNNClassifier\pipeline\stage_03_model_training.py
            - config\config.yaml
            - artifacts\data_injection\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone
            - artifacts\prepare_base_model\base_model.h5
        params:
            - IMAGE_SIZE
            - CLASSES
            - EPOCHS
            - BATCH_SIZE
            - LEARNING_RATE
            - AUGMENTATION
        outs:
            - artifacts\training\model.h5

    evaluation:
        cmd: python src\CNNClassifier\pipeline\stage_04_model_evaluation.py
        deps:
            - src\CNNClassifier\pipeline\stage_04_model_evaluation.py
            - config\config.yaml
            - artifacts\data_injection\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone
            - artifacts\training\model.h5
        params:
            - IMAGE_SIZE
            - CLASSES
            - EPOCHS
            - BATCH_SIZE
            - LEARNING_RATE
            - AUGMENTATION
        metrics:
            - score.json:
                cache: false
