artifacts_root: artifacts

data_injection:
  root_dir: artifacts/data_injection
  source_URL: "https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1"
  local_data_file: artifacts/data_injection/data.zip
  unzip_dir: artifacts/data_injection